apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: drakemall-tracker-job
spec:
  schedule: "0 7,13 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3

  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
            - name: drakemall-prerender-job
              image: registry.gitlab.com/drake-reppo/delivery-tracker:$CI_COMMIT_REF_NAME
              imagePullPolicy: IfNotPresent
              env:
                - name: API_URL
                  value: "$API_URL"
                - name: API_USER_EMAIL
                  value: "$API_USER_EMAIL"
                - name: API_USER_PASSWORD
                  value: "$API_USER_PASSWORD"
                - name: TRACKING_STATUS_SELECTOR
                  value: "$TRACKING_STATUS_SELECTOR"
                - name: TRACKING_URL
                  value: "$TRACKING_URL"
                - name: SLACK_WEBHOOK_URL
                  value: "$SLACK_WEBHOOK_URL"
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: gitlab-container-registry
