image: docker:19.03.12

services:
  - docker:19.03.12-dind

build:
  stage: build
  before_script:
    - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - apk add --no-cache docker-compose
    - touch .env
    - docker-compose build delivery-tracker
    - docker-compose push delivery-tracker
  only:
    - tags
  except:
    - branches

deploy:
  stage: deploy
  image: dtzar/helm-kubectl
  before_script:
    - mkdir ~/.kube && echo $KUBECONFIG_PROD | base64 -d > ~/.kube/config
  script:
    - apk add --no-cache gettext && envsubst < .k8s/deployment.yml | kubectl apply -f -
  only:
    - tags
  except:
    - branches
