version: "3.6"

services:
  tracker:
    image: ${CI_REGISTRY_IMAGE:-registry.gitlab.com/drake-reppo/delivery-tracker}:${CI_COMMIT_REF_NAME:-latest}
    build:
      context: .
    env_file:
      - .env


