version: "3.6"

services:
  tracker:
    image: registry.gitlab.com/drake-reppo/delivery-tracker:v1.2.1
    build:
      context: .
    expose:
      - 9229
    ports:
      - 9224:9229
    env_file: .env


